---
- name: Create AFNI directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/opt/quarantine/software/afni/{{ ansible_date_time.date }}/install"

- name: Install AFNI dependencies
  ansible.builtin.pacman:
    update_cache: true
    state: present
    pkg:
      - tcsh
      - xorg-fonts-alias
      - openssl
      - python
      - python-matplotlib
      - python-numpy
      - python-flask
      - python-flask-cors
      - python-pillow
      - gsl
      - netpbm
      - libjpeg-turbo
      - xorg-server-xvfb
      - mesa
      - libglvnd
      - libxmu
      - base-devel
      - curl
      - libxml2
      - gcc-fortran
      - gomp
      - xorg-fonts-100dpi
      - cmake
      - gdal
      - openblas
      - nodejs
      - udunits

# Fix AFNI being built against a different version of gsl
# https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu22.html#id4
- name: Link GSL library for AFNI to work
  file:
    src: /usr/lib/libgsl.so.27
    dest: /usr/lib/libgsl.so.19
    state: link

- name: Download AFNI installer
  get_url:
    url: https://afni.nimh.nih.gov/pub/dist/bin/misc/@update.afni.binaries
    dest: /tmp/@update.afni.binaries

- name: Run AFNI Installer
  shell: tcsh /tmp/@update.afni.binaries -package linux_ubuntu_16_64 -apsearch yes -bindir /opt/quarantine/software/afni/{{ ansible_date_time.date }}/install
  args:
    creates: /opt/quarantine/software/afni/{{ ansible_date_time.date }}/install/afni

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/afni/{{ ansible_date_time.date }}/module
  notify: link modules
